name: Repo dispatch receiver
on: repository_dispatch
jobs:
  echo_something:
    runs-on: ubuntu-latest
    steps:
      - name: Echo received data
        env:
          MESSAGE: ${{ github.event.client_payload.hash }}
        run: |
          echo "Hash received is ${MESSAGE}"
